name: ci

on:
  workflow_dispatch:

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    name: setup freebsd vm and run test
    steps:
    - name: test in freebsd
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
            pkg install -y bash
            pkg install -y wget
        run: |
          pwd
  test-openbsd:
    runs-on: ubuntu-latest
    name: setup openbsd vm and run test
    steps:
    - name: test in openbsd
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
            pkg_add bash
            pkg_add wget
        run: |
          pwd
